### ISSUE TITLE
Camera does not follow player model

### ISSUE THREAD

**Issue by habeeb-umo** [csugda/vega#22]
To recreate bug:

Add a rigidbody component to the model and run into a wall. The camera keeps moving while the player is still.

**Comment by JonathanGriego** [comment]
I have a fix for this, but my version of the game would include the TapToMove script that seems not to be merging properly (see Jgriego-Patch2-TapToMove #20).

**Comment by dhallstr** [comment]
Would moving the CapsuleCollider from the PlayerModel object to the Player object fix it?

**Comment by dhallstr** [comment]
Verified. The only that needs to be done is put the Collider and Rigidbody on the Player object. Will add that to my current Pull Request.
